# Generated by Django 3.0.3 on 2020-06-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_monitoring', '0002_devicemonitoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemonitoring',
            name='disabled_checks',
            field=models.BooleanField(
                default=False, help_text='disables all checks for the device',
            ),
        ),
    ]
